window.env = {
  "NVM_INC": "/Users/lb8/.nvm/versions/node/v18.17.1/include/node",
  "TERM_PROGRAM": "vscode",
  "NODE": "/Users/lb8/.nvm/versions/node/v18.17.1/bin/node",
  "NVM_CD_FLAGS": "-q",
  "INIT_CWD": "/Users/lb8/Documents/GitHub/sportsee-lucas",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "TMPDIR": "/var/folders/ky/fmrgxvg91kn_9ymcnhswkq_r0000gn/T/",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_global_prefix": "/Users/lb8/.nvm/versions/node/v18.17.1",
  "TERM_PROGRAM_VERSION": "1.72.2",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "ZDOTDIR": "/Users/lb8",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/lb8/Documents/GitHub/sportsee-lucas",
  "USER": "lb8",
  "NVM_DIR": "/Users/lb8/.nvm",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/Users/lb8/.nvm/versions/node/v18.17.1/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.tJs7WEguay/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x1",
  "npm_execpath": "/Users/lb8/.nvm/versions/node/v18.17.1/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/lb8/Documents/GitHub/sportsee-lucas/node_modules/.bin:/Users/lb8/Documents/GitHub/node_modules/.bin:/Users/lb8/Documents/node_modules/.bin:/Users/lb8/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/lb8/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/lb8/Documents/GitHub/sportsee-lucas/node_modules/.bin:/Users/lb8/Documents/GitHub/node_modules/.bin:/Users/lb8/Documents/node_modules/.bin:/Users/lb8/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/lb8/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/lb8/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/bin:/Users/lb8/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin",
  "_": "/Users/lb8/Documents/GitHub/sportsee-lucas/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/lb8/Documents/GitHub/sportsee-lucas/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "USER_ZDOTDIR": "/Users/lb8",
  "npm_config_init_module": "/Users/lb8/.npm-init.js",
  "npm_config_userconfig": "/Users/lb8/.npmrc",
  "PWD": "/Users/lb8/Documents/GitHub/sportsee-lucas",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "fr_FR.UTF-8",
  "npm_package_name": "sportsee-lucas",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "npm_config_node_gyp": "/Users/lb8/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "VSCODE_INJECTION": "1",
  "HOME": "/Users/lb8",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/private/var/folders/ky/fmrgxvg91kn_9ymcnhswkq_r0000gn/T/AppTranslocation/A31711F4-6D89-49B2-BF5E-40150E6286F1/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "LOGNAME": "lb8",
  "npm_config_cache": "/Users/lb8/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/ky/fmrgxvg91kn_9ymcnhswkq_r0000gn/T/vscode-git-14298fbc43.sock",
  "NVM_BIN": "/Users/lb8/.nvm/versions/node/v18.17.1/bin",
  "npm_config_user_agent": "npm/9.6.7 node/v18.17.1 darwin x64 workspaces/false",
  "GIT_ASKPASS": "/private/var/folders/ky/fmrgxvg91kn_9ymcnhswkq_r0000gn/T/AppTranslocation/A31711F4-6D89-49B2-BF5E-40150E6286F1/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/private/var/folders/ky/fmrgxvg91kn_9ymcnhswkq_r0000gn/T/AppTranslocation/A31711F4-6D89-49B2-BF5E-40150E6286F1/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper",
  "DISPLAY": "/private/tmp/com.apple.launchd.kwrd9bJQaw/org.xquartz:0",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/Users/lb8/.nvm/versions/node/v18.17.1",
  "npm_node_execpath": "/Users/lb8/.nvm/versions/node/v18.17.1/bin/node",
  "REACT_APP_API_APIUSE": "true",
  "REACT_APP_API_USER": "user/12",
  "REACT_APP_API_ACTIVITY": "user/12/activity",
  "REACT_APP_API_PERFORMANCE": "user/12/performance",
  "REACT_APP_API_SESSION": "user/12/average-sessions"
};